version: "3.7"
services:
  movie-api:
    image: movie-api
    build: ./api
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "5555"]

  movie-proxy:
    image: nginx:1.21.6-alpine
    volumes:
      - "./api/nginx.conf:/etc/nginx/conf.d/default.conf"
    command: ["nginx", "-g", "daemon off;"]
    ports:
      - "127.0.0.1:5555:5555"
